package core

type attachedCategory struct {
	id, name, value, path string
}

type attachedProvider struct {
	id, name, base, kind string
	search               bool
	categories           []attachedCategory
}

var attachedProviders = []attachedProvider{
	{id: "xiaobao", name: "小宝影院", base: "https://www.xiaobaotv.com", kind: "html", search: true, categories: []attachedCategory{
		{"1", "电影", "1", ""},
		{"2", "电视剧", "2", ""},
		{"3", "动漫", "3", ""},
		{"4", "综艺", "4", ""},
		{"11", "短剧", "11", ""},
	}},
	{id: "batvideo", name: "蝙蝠视频", base: "https://257915.xyz", kind: "html", search: true, categories: []attachedCategory{
		{"64360061", "线路1·中文字幕", "64360061", ""},
		{"64370061", "线路1·网红主播", "64370061", ""},
		{"64380061", "线路1·成人动漫", "64380061", ""},
		{"64390061", "线路1·欧美情色", "64390061", ""},
		{"64400061", "线路1·国模私拍", "64400061", ""},
		{"64430061", "线路1·韩国伦理", "64430061", ""},
		{"64170061", "线路1·国产情色", "64170061", ""},
		{"64180061", "线路1·日本无码", "64180061", ""},
		{"64170041", "线路2·日韩无码", "64170041", ""},
		{"64190041", "线路2·欧美精品", "64190041", ""},
		{"64200041", "线路2·国产精品", "64200041", ""},
		{"64340041", "线路2·中文字幕", "64340041", ""},
		{"64360041", "线路2·动漫精品", "64360041", ""},
		{"64390041", "线路2·日韩精品", "64390041", ""},
		{"64580041", "线路2·大秀视频", "64580041", ""},
		{"64360111", "线路3·精品推荐", "64360111", ""},
		{"64380111", "线路3·国产色情", "64380111", ""},
		{"64390111", "线路3·主播直播", "64390111", ""},
		{"64630111", "线路3·91探花", "64630111", ""},
		{"64750111", "线路3·传媒出品", "64750111", ""},
		{"64530111", "线路3·日本精品", "64530111", ""},
		{"64460111", "线路3·欧美精品", "64460111", ""},
		{"64170031", "线路4·国产自拍", "64170031", ""},
		{"64180031", "线路4·欧美极品", "64180031", ""},
		{"64190031", "线路4·日韩无码", "64190031", ""},
		{"64360031", "线路4·中文字幕", "64360031", ""},
		{"64370031", "线路4·动漫精品", "64370031", ""},
		{"64410031", "线路4·三级自慰", "64410031", ""},
	}},
	{id: "honeypeach", name: "暗黑蜜桃", base: "https://honeypeach.cc", kind: "api", search: true, categories: []attachedCategory{
		{"video", "蜜桃视频", "video", ""},
		{"video~new", "蜜桃视频·最近更新", "video@@new", ""},
		{"video~release", "蜜桃视频·新作上市", "video@@release", ""},
		{"video~chinese-subtitle", "蜜桃视频·中文字幕", "video@@chinese-subtitle", ""},
		{"video~madou", "蜜桃视频·麻豆传媒", "video@@madou", ""},
		{"video~uncensored-leak", "蜜桃视频·无码流出", "video@@uncensored-leak", ""},
		{"video~fc2", "蜜桃视频·FC2", "video@@fc2", ""},
		{"video~monthly-hot", "蜜桃视频·热门", "video@@monthly-hot", ""},
		{"video~genres-VR", "蜜桃视频·VR", "video@@genres/VR", ""},
		{"video~heyzo", "蜜桃视频·HEYZO", "video@@heyzo", ""},
		{"video~tokyohot", "蜜桃视频·东京热", "video@@tokyohot", ""},
		{"video~1pondo", "蜜桃视频·一本道", "video@@1pondo", ""},
		{"video~caribbeancom", "蜜桃视频·Caribbeancom", "video@@caribbeancom", ""},
		{"video~caribbeancompr", "蜜桃视频·Caribbeancompr", "video@@caribbeancompr", ""},
		{"video~siro", "蜜桃视频·SIRO", "video@@siro", ""},
		{"video~luxu", "蜜桃视频·LUXU", "video@@luxu", ""},
		{"video~twav", "蜜桃视频·TWAV", "video@@twav", ""},
		{"video~furuke", "蜜桃视频·Furuke", "video@@furuke", ""},
		{"video~today-hot", "蜜桃视频·今日热门", "video@@today-hot", ""},
		{"video~weekly-hot", "蜜桃视频·本週热门", "video@@weekly-hot", ""},
		{"duanju", "蜜桃短剧", "duanju", ""},
		{"duanju~all", "蜜桃短剧·精选", "duanju@@all", ""},
		{"duanju~chiguo", "蜜桃短剧·赤果短剧", "duanju@@chiguo", ""},
		{"duanju~mod", "蜜桃短剧·魔改短剧", "duanju@@mod", ""},
		{"duanju~yuandou", "蜜桃短剧·黄豆原创", "duanju@@yuandou", ""},
		{"duanju~zhenren", "蜜桃短剧·真人短剧", "duanju@@zhenren", ""},
		{"duanju~erciyuan", "蜜桃短剧·动漫", "duanju@@erciyuan", ""},
		{"duanju~aiman", "蜜桃短剧·影院", "duanju@@aiman", ""},
		{"duanju~tuijian", "蜜桃短剧·推荐", "duanju@@tuijian", ""},
		{"duanju~duanju", "蜜桃短剧·AI成人短剧", "duanju@@duanju", ""},
		{"duanju~manju", "蜜桃短剧·AI成人漫剧", "duanju@@manju", ""},
		{"duanju~huanlian", "蜜桃短剧·AI换脸", "duanju@@huanlian", ""},
		{"duanju~mogai", "蜜桃短剧·AI魔改", "duanju@@mogai", ""},
		{"duanju~rank", "蜜桃短剧·排行榜", "duanju@@rank", ""},
		{"duanju~pengran", "蜜桃短剧·怦然心动", "duanju@@pengran", ""},
		{"caibian", "擦边短剧", "caibian", ""},
		{"caibian~0", "擦边短剧·最新", "caibian@@0", ""},
		{"caibian~1", "擦边短剧·推荐", "caibian@@1", ""},
		{"caibian~2", "擦边短剧·全部", "caibian@@2", ""},
		{"shortv", "蜜桃动漫", "shortv", ""},
		{"shortv~all", "蜜桃动漫·全部", "shortv@@all", ""},
		{"shortv~Hanime", "蜜桃动漫·Hanime", "shortv@@Hanime", ""},
		{"shortv~NaughtyMachinima", "蜜桃动漫·NaughtyMachinima", "shortv@@NaughtyMachinima", ""},
		{"shortv~HS日本4K动漫", "蜜桃动漫·HS日本4K动漫", "shortv@@HS日本4K动漫", ""},
		{"guochan", "国产精品", "guochan", ""},
		{"heiliao", "黑料吃瓜", "heiliao", ""},
		{"heiliao~0", "黑料吃瓜·最新", "heiliao@@0", ""},
		{"heiliao~1", "黑料吃瓜·推荐", "heiliao@@1", ""},
		{"live", "蜜桃直播", "live", ""},
		{"live~girls", "蜜桃直播·女主播", "live@@girls", ""},
		{"live~couples", "蜜桃直播·情侣", "live@@couples", ""},
		{"live~men", "蜜桃直播·男主播", "live@@men", ""},
		{"live~trans", "蜜桃直播·跨性别", "live@@trans", ""},
		{"live~cn", "蜜桃直播·中国", "live@@cn", ""},
		{"live~jp", "蜜桃直播·日本", "live@@jp", ""},
		{"live~kr", "蜜桃直播·韩国", "live@@kr", ""},
		{"live~us", "蜜桃直播·美国", "live@@us", ""},
		{"live~th", "蜜桃直播·泰国", "live@@th", ""},
		{"live~vn", "蜜桃直播·越南", "live@@vn", ""},
		{"live~ru", "蜜桃直播·俄罗斯", "live@@ru", ""},
	}},
	{id: "weiguan", name: "围观", base: "https://api.drama.9ddm.com", kind: "api", search: true, categories: []attachedCategory{
		{"recommend", "推荐", "recommend", ""},
	}},
	{id: "hema", name: "河马", base: "https://freevideo.zqqds.cn", kind: "api", search: true, categories: []attachedCategory{
		{"jingxuan", "精选", "53", ""},
		{"guzhuang", "古装", "54", ""},
		{"chongsheng", "重生", "55", ""},
		{"jiating", "家庭", "56", ""},
		{"lianai", "恋爱", "57", ""},
	}},
	{id: "shanhai", name: "山海", base: "https://api.app.gxshxy.com", kind: "api", search: true, categories: []attachedCategory{
		{"jingxuan", "精选", "0", ""},
		{"renqi", "人气", "1", ""},
		{"xinju", "新剧", "51", ""},
		{"tianchong", "甜宠", "46", ""},
		{"nixi", "逆袭", "6", ""},
		{"qiangzhe", "强者回归", "50", ""},
		{"qihuan", "奇幻", "44", ""},
		{"fuchou", "复仇", "49", ""},
		{"zhongguomeng", "中国梦", "41", ""},
		{"jiating", "家庭", "9", ""},
	}},
	{id: "haokan", name: "好看", base: "https://sv.baidu.com", kind: "api", search: false, categories: []attachedCategory{
		{"reboduanju", "热播剧", "1", ""},
		{"xinju", "新剧", "2", ""},
		{"zhanshen", "战神", "1001", ""},
		{"shenhao", "神豪", "2001", ""},
		{"shenyi", "神医", "1002", ""},
		{"tianchong", "甜宠", "1007", ""},
		{"zhuixu", "赘婿", "1003", ""},
		{"chuanyue", "穿越重生", "2004", ""},
		{"yineng", "异能", "2005", ""},
		{"nuelian", "虐恋", "1006", ""},
		{"gongdou", "宫斗宅斗", "2006", ""},
		{"xuanhuan", "玄幻", "2009", ""},
	}},
	{id: "baidu", name: "百度", base: "https://mbd.baidu.com", kind: "api", search: false, categories: []attachedCategory{
		{"quanbu", "全部", "quanbu", ""},
		{"shenyi", "神医", "shenyi", ""},
		{"dushi", "都市", "dushi", ""},
		{"xiandaiyanqing", "现代言情", "xiandaiyanqing", ""},
		{"yineng", "异能", "yineng", ""},
		{"nixi", "逆袭", "nixi", ""},
		{"tianchong", "甜宠", "tianchong", ""},
		{"zongcai", "总裁", "zongcai", ""},
		{"mengbao", "萌宝", "mengbao", ""},
		{"zhanshen", "战神", "zhanshen", ""},
		{"gongdouzhaidou", "宫斗宅斗", "gongdouzhaidou", ""},
		{"shenhao", "神豪", "shenhao", ""},
		{"nuelian", "虐恋", "nuelian", ""},
		{"shanhun", "闪婚", "shanhun", ""},
		{"xuanhuan", "玄幻", "xuanhuan", ""},
		{"chuanyuechongsheng", "穿越重生", "chuanyuechongsheng", ""},
		{"niandai", "年代", "niandai", ""},
		{"jiatinglunli", "家庭伦理", "jiatinglunli", ""},
		{"gudaiyanqing", "古代言情", "gudaiyanqing", ""},
		{"wuxiawuda", "武侠武打", "wuxiawuda", ""},
		{"zhuixu", "赘婿", "zhuixu", ""},
		{"qingchunxiaoyuan", "青春校园", "qingchunxiaoyuan", ""},
	}},
	{id: "xingya", name: "星芽", base: "https://app.whjzjx.cn", kind: "api", search: true, categories: []attachedCategory{
		{"juchang", "剧场", "1", ""},
		{"reboduanju", "热播剧", "2", ""},
		{"huiyuan", "会员专享", "8", ""},
		{"xingxuan", "星选好剧", "7", ""},
		{"xinju", "新剧", "3", ""},
		{"yangguang", "阳光剧场", "5", ""},
	}},
	{id: "qimao", name: "七猫", base: "https://api-store.qmplaylet.com", kind: "api", search: true, categories: []attachedCategory{
		{"0", "推荐", "0", ""},
		{"-1", "新剧", "-1", ""},
		{"1273", "都市情感", "1273", ""},
		{"1272", "古装", "1272", ""},
		{"571", "都市", "571", ""},
		{"1286", "玄幻仙侠", "1286", ""},
		{"570", "奇幻", "570", ""},
		{"590", "乡村", "590", ""},
		{"573", "民国", "573", ""},
		{"572", "年代", "572", ""},
		{"1288", "青春校园", "1288", ""},
		{"371", "武侠", "371", ""},
		{"594", "科幻", "594", ""},
		{"556", "末世", "556", ""},
		{"1289", "二次元", "1289", ""},
		{"400", "逆袭", "400", ""},
		{"373", "穿越", "373", ""},
		{"795", "复仇", "795", ""},
		{"787", "系统", "787", ""},
		{"790", "权谋", "790", ""},
		{"784", "重生", "784", ""},
		{"1294", "女性成长", "1294", ""},
		{"716", "打脸虐渣", "716", ""},
		{"480", "闪婚", "480", ""},
		{"402", "强者回归", "402", ""},
		{"715", "追妻火葬场", "715", ""},
		{"670", "家庭", "670", ""},
		{"558", "马甲", "558", ""},
		{"724", "职场", "724", ""},
		{"343", "宫斗", "343", ""},
		{"1299", "高手下山", "1299", ""},
		{"1295", "娱乐明星", "1295", ""},
		{"727", "异能", "727", ""},
		{"342", "宅斗", "342", ""},
		{"712", "替身", "712", ""},
		{"338", "穿书", "338", ""},
		{"723", "商战", "723", ""},
		{"1291", "种田经商", "1291", ""},
		{"1293", "伦理", "1293", ""},
		{"1290", "社会话题", "1290", ""},
		{"492", "致富", "492", ""},
		{"1258", "偷听心声", "1258", ""},
		{"526", "脑洞", "526", ""},
		{"624", "豪门总裁", "624", ""},
		{"356", "萌宝", "356", ""},
		{"527", "战神", "527", ""},
		{"812", "真假千金", "812", ""},
		{"36", "赘婿", "36", ""},
		{"1269", "神医", "1269", ""},
		{"37", "神豪", "37", ""},
		{"1296", "小人物", "1296", ""},
		{"545", "团宠", "545", ""},
		{"464", "欢喜冤家", "464", ""},
		{"617", "女帝", "617", ""},
		{"1297", "银发", "1297", ""},
		{"28", "兵王", "28", ""},
		{"16", "虐恋", "16", ""},
		{"21", "甜宠", "21", ""},
		{"27", "悬疑", "27", ""},
		{"793", "搞笑", "793", ""},
		{"1287", "灵异", "1287", ""},
	}},
	{id: "damang", name: "大芒", base: "https://damang.api.mgtv.com", kind: "api", search: true, categories: []attachedCategory{
		{"aiqing", "爱情", "1273154", ""},
		{"dushi", "都市", "1279863", ""},
		{"guzhuang", "古装", "1273153", ""},
		{"yanqing", "言情", "1273190", ""},
		{"qihuan", "奇幻", "2924543", ""},
		{"zhenrenxiu", "真人秀", "1657120", ""},
		{"xuanyi", "悬疑", "1310272", ""},
		{"wangju", "网剧", "2844459", ""},
		{"qingchun", "青春", "2836677", ""},
	}},
	{id: "xifan", name: "西饭", base: "https://xifan-api-cn.youlishipin.com", kind: "api", search: true, categories: []attachedCategory{
		{"dushi", "都市", "68@都市", ""},
		{"qingchun", "青春", "68@青春", ""},
		{"xiandaiyanqing", "现代言情", "81@现代言情", ""},
		{"haomen", "豪门", "81@豪门", ""},
		{"danvzhu", "大女主", "80@大女主", ""},
		{"nixi", "逆袭", "79@逆袭", ""},
		{"dalianuecha", "打脸虐渣", "79@打脸虐渣", ""},
		{"chuanyue", "穿越", "81@穿越", ""},
	}},
	{id: "xingxing", name: "星星", base: "http://read.api.duodutek.com", kind: "api", search: false, categories: []attachedCategory{
		{"jingxuan", "精选", "1287", ""},
		{"remen", "热门", "1288", ""},
		{"xinju", "新剧", "1289", ""},
	}},
	{id: "yimi", name: "薏米", base: "https://yimi-api.zhangyue.com", kind: "api", search: false, categories: []attachedCategory{
		{"jingxuan", "精选", "channel_c6f50cd9", ""},
		{"nixi", "逆袭", "channel_a8e10abc", ""},
		{"fuchou", "复仇", "channel_d26dd434", ""},
		{"lianai", "恋爱", "channel_75afe84a", ""},
		{"chongsheng", "重生", "channel_2272aac5", ""},
		{"gufeng", "古风", "channel_73190d4f", ""},
		{"shenyi", "神医", "channel_2d7eae6b", ""},
		{"yanqing", "言情", "channel_614820bd", ""},
		{"dushi", "都市", "channel_13dfce8b", ""},
		{"xuanyi", "悬疑", "channel_861b9642", ""},
		{"lishi", "历史", "channel_18157927", ""},
	}},
	{id: "wusheng", name: "悟圣", base: "http://read.api.duodutek.com", kind: "api", search: false, categories: []attachedCategory{
		{"1287", "甜宠", "1287", ""},
		{"1288", "逆袭", "1288", ""},
		{"1289", "热血", "1289", ""},
		{"1290", "现代", "1290", ""},
		{"1291", "古代", "1291", ""},
	}},
	{id: "qixing", name: "七星", base: "https://app.whjzjx.cn", kind: "api", search: true, categories: []attachedCategory{
		{"1", "剧场", "1", ""},
		{"3", "新剧", "3", ""},
		{"2", "热播", "2", ""},
		{"7", "星选", "7", ""},
		{"5", "阳光", "5", ""},
	}},
	{id: "kuwo", name: "酷我", base: "http://wapi.kuwo.cn/openapi/v1/shortplay", kind: "api", search: false, categories: []attachedCategory{
		{"10", "猜你想看", "10", ""},
		{"11", "土味爱情", "11", ""},
		{"12", "更多精彩", "12", ""},
		{"13", "霸道总裁的人生", "13", ""},
		{"14", "赘婿当道", "14", ""},
		{"15", "漫漫追妻路", "15", ""},
		{"16", "家庭情感", "16", ""},
	}},
	{id: "niuniudj", name: "牛牛短剧", base: "https://new.tianjinzhitongdaohe.com", kind: "api", search: true, categories: []attachedCategory{
		{"现言", "现言", "现言", ""},
		{"古言", "古言", "古言", ""},
		{"历史", "历史", "历史", ""},
		{"都市", "都市", "都市", ""},
		{"亲情", "亲情", "亲情", ""},
		{"玄幻", "玄幻", "玄幻", ""},
		{"热血", "热血", "热血", ""},
		{"动作", "动作", "动作", ""},
		{"喜剧", "喜剧", "喜剧", ""},
		{"悬疑", "悬疑", "悬疑", ""},
		{"军事", "军事", "军事", ""},
		{"二次元", "二次元", "二次元", ""},
		{"其他剧情", "其他剧情", "其他剧情", ""},
	}},
	{id: "souju", name: "搜剧AI", base: "https://souju.ai", kind: "api", search: true, categories: []attachedCategory{
		{"脑洞悬疑", "脑洞悬疑", "脑洞悬疑", ""},
		{"古装仙侠", "古装仙侠", "古装仙侠", ""},
		{"现代都市", "现代都市", "现代都市", ""},
		{"女频恋爱", "女频恋爱", "女频恋爱", ""},
		{"言情总裁", "言情总裁", "言情总裁", ""},
		{"年代穿越", "年代穿越", "年代穿越", ""},
		{"现代言情", "现代言情", "现代言情", ""},
		{"反转爽剧", "反转爽剧", "反转爽剧", ""},
		{"重生民国", "重生民国", "重生民国", ""},
	}},
	{id: "wuwu", name: "五五", base: "https://www.duanju55.com", kind: "html", search: true, categories: []attachedCategory{
		{"全部", "全部", "全部", ""},
		{"男频", "男频", "男频", ""},
		{"女频", "女频", "女频", ""},
		{"都市", "都市", "都市", ""},
		{"虐渣", "虐渣", "虐渣", ""},
		{"励志", "励志", "励志", ""},
		{"逆袭", "逆袭", "逆袭", ""},
		{"古风", "古风", "古风", ""},
		{"复仇", "复仇", "复仇", ""},
		{"家庭", "家庭", "家庭", ""},
		{"悬疑", "悬疑", "悬疑", ""},
		{"奇幻", "奇幻", "奇幻", ""},
	}},
	{id: "huangdou2", name: "黄豆2", base: "https://aihuangdou.com", kind: "html", search: true, categories: []attachedCategory{
		{"home", "首页", "home", ""},
		{"ai-duanju", "AI短剧", "ai-duanju", ""},
		{"ai-manju", "AI漫剧", "ai-manju", ""},
		{"rankings", "榜单", "rankings", ""},
	}},
	{id: "dj51", name: "51短剧", base: "https://arab.bqdikpcrx.cc", kind: "html", search: false, categories: []attachedCategory{
		{"rank", "总榜", "rank", "/rank/"},
		{"new", "最新剧场", "new", "/new-theater-category/"},
		{"tag:51原创", "51原创", "tag:51原创", "/tag/51原创/"},
		{"tag:AI短剧", "AI短剧", "tag:AI短剧", "/tag/AI短剧/"},
		{"tag:成人", "成人", "tag:成人", "/tag/成人/"},
		{"tag:原创", "原创", "tag:原创", "/tag/原创/"},
	}},
	{id: "chengguo", name: "橙果", base: "https://chengguodj.com", kind: "html", search: true, categories: []attachedCategory{
		{"yuanchuang", "原创", "yuanchuang", "/yuanchuang"},
		{"mogai", "魔改", "mogai", "/mogai"},
		{"manju", "漫剧", "manju", "/manju"},
		{"zhenren", "真人", "zhenren", "/zhenren"},
		{"aiduanju", "AI短剧", "aiduanju", "/aiduanju"},
		{"browse", "全部", "browse", "/browse"},
	}},
	{id: "xiangjiao", name: "香蕉", base: "https://xiangjiaoai.ai", kind: "api", search: true, categories: []attachedCategory{
		{"hot", "精选推荐", "hot", ""},
		{"theater", "全部剧场", "theater", ""},
		{"cat:明星换脸", "明星换脸", "cat:明星换脸", ""},
		{"cat:影视魔改", "影视魔改", "cat:影视魔改", ""},
		{"cat:动漫游戏", "动漫游戏", "cat:动漫游戏", ""},
		{"cat:穿越重生", "穿越重生", "cat:穿越重生", ""},
		{"cat:系统异能", "系统异能", "cat:系统异能", ""},
		{"cat:仙侠修真", "仙侠修真", "cat:仙侠修真", ""},
		{"cat:古装权谋", "古装权谋", "cat:古装权谋", ""},
	}},
	{id: "huanggua", name: "黄瓜", base: "https://hgdju4.com", kind: "html", search: false, categories: []attachedCategory{
		{"recommend", "推荐", "recommend", "/"},
		{"yuanchuang", "原创", "yuanchuang", "/yuanchuang"},
		{"mogai", "魔改", "mogai", "/mogai"},
		{"manju", "AI漫剧", "manju", "/manju"},
		{"zhenren", "真人短剧", "zhenren", "/zhenren"},
		{"aiduanju", "AI短剧", "aiduanju", "/aiduanju"},
		{"browse", "全部", "browse", "/browse"},
		{"browse-new", "最新", "browse-new", "/browse?sort=new"},
	}},
	{id: "kuangbiao", name: "狂飙", base: "https://ai.dramarush.tv", kind: "api", search: false, categories: []attachedCategory{
		{"t-5jxcit", "短剧", "t-5jxcit", ""},
		{"normal_short", "正规短剧", "normal_short", ""},
		{"adult_short", "成人短剧", "adult_short", ""},
	}},
	{id: "dj91", name: "91", base: "https://91crdj.com", kind: "html", search: true, categories: []attachedCategory{
		{"duanju", "短剧", "duanju", ""},
		{"manju", "漫剧", "manju", ""},
		{"zhenrenju", "真人剧", "zhenrenju", ""},
		{"shipin", "视频", "shipin", ""},
		{"paihang", "排行", "paihang", ""},
		{"biaoqian:aiduanju", "AI短剧", "biaoqian:aiduanju", ""},
	}},
	{id: "md2048", name: "2048", base: "https://2048ai.vip", kind: "api", search: false, categories: []attachedCategory{
		{"cat-29", "AI短剧", "cat-29", ""},
		{"cat-6", "麻豆原创AI", "cat-6", ""},
		{"cat-9", "麻豆传媒", "cat-9", ""},
		{"cat-2", "AV中文字幕", "cat-2", ""},
		{"cat-14", "重口调教", "cat-14", ""},
		{"cat-19", "黑料吃瓜", "cat-19", ""},
	}},
	{id: "duanjuone", name: "短剧one", base: "https://duanju.one", kind: "html", search: true, categories: []attachedCategory{
		{"free", "免费", "free", ""},
		{"vip", "VIP/积分", "vip", ""},
	}},
	{id: "yizk", name: "一直看", base: "https://1zk.top", kind: "api", search: true, categories: []attachedCategory{
		{"sqqsfvqirt0c", "华语", "sqqsfvqirt0c", ""},
		{"jr4jltgb5bct", "东瀛", "jr4jltgb5bct", ""},
		{"967tfsdaht5i", "欧美", "967tfsdaht5i", ""},
		{"ovamj5o7x0gs", "三级", "ovamj5o7x0gs", ""},
		{"fs7hmy32jqfm", "Ai短剧", "fs7hmy32jqfm", ""},
	}},
}
